### ISSUE TITLE
an option to not die on errors?

### ISSUE THREAD

**Issue by ctophs** [L11R/escobar#24]
Hi,
can I tell escobar to not die on errors reaching downstream proxy but retry? On my system there is a timeframe when escobar is already started but network flaps once or twice which often leads to escobar shutting down.

It is started from within wsl2 (and I do not use a service supervisor like systemd there that would be able to fix it by itsself). Yes, wsl is a pain..

**Comment by L11R** [comment]
@ctophs yes, it's reasonable to fix. You can send me PR, if it's not urgent.

**Comment by ctophs** [comment]
I was thinking of a loop around net.DialTimeout() within connectAndCopy (proxy.go#L263) using a configurable number of repetitions because the CheckAuth also does useful things in case of a reachable proxy server?
